### ISSUE TITLE
Cant use commands in private messages with the bot

### ISSUE THREAD

**Issue by MiloIssueTracker** [RubenJ01/MiloBot#18]
## Steps to Reproduce
Try using a command in a private message with the bot
## Severity
2
## Additional Information
No
## Author
`RubenJ01`: 391583287652515841

**Comment by gaborszita** [comment]
Do we really want this? It's important to note though that big bots, like MEE6 and Dyno also don't support commands in private messages (try it). I'm not saying none of the commands should work in private messages, I'm just saying that we shouldn't make all commands work. For example, checking stats and playing blackjack would be fine in private messages. But playing poker and hungergames, which requires a lobby, shouldn't work in private messages.

I already have an idea for the whole message and button handling system (or whatever it is called) of how we can refactor it to make it look much more nice and incorporating which commands would work in private messages could be added to it.

**Comment by RubenJ01** [comment]
Preferably we would have some sort of setting like `allowDm` or something like that which defaults to 0 and then inside of the commands constructor you could set it to true, making the command work in dm's

**Comment by gaborszita** [comment]
> Preferably we would have some sort of setting like `allowDm` or something like that which defaults to false and then inside of the commands constructor you could set it to true, making the command work in dm's

That's also what I thought we could do.

**Comment by gaborszita** [comment]
Set to be fixed in the new command handler.

**Comment by gaborszita** [comment]
With the new command handler, commands can now be used in private messages.

Closing
