### ISSUE TITLE
Lobby fixes

### ISSUE THREAD

**Issue by gaborszita** [RubenJ01/MiloBot#30]
There are the changes that I think should be done in the Lobby class:

1. Lobby should store the User objects, instead of the user ids and names. The User object contains all information about users. When I star the poker game, I need all the user objects of the user, so I have to use jda.retrieveUser(userId), which is a RestAction, so it's seems like wasted time and resources querying user data.
2. Lobby should have one, universal constructor taking three parameters: User object, min players and max players.
3. Lobby should display users as mentions, rather than their names.

**Comment by gaborszita** [comment]
In progress by new lobby implementation. When hunger games implements the new lobby, this issue can be solved.

**Comment by RubenJ01** [comment]
Solved in pull request #39
