### ISSUE TITLE
If the user is already in a blackjack game and tries to play another game, the bot will detect that he is already in a game, but will deduct the bet from his balance.

### ISSUE THREAD

**Issue by MiloIssueTracker** [RubenJ01/MiloBot#71]
## Steps to Reproduce
Try playing a blackjack game with a bet and using the play command again with a bet. On the second command the boy reply saying that you are already in a blackjack game, but will deduct the bet from your balance.
## Severity
4
## Additional Information
No
## Author
`OtherCards#7157`: 709849160832122910

**Comment by gaborszita** [comment]
This should be fixed by #73 and #76.
